package com.chatassistant.aichatassistant.bench;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Renders the benchmark report.
 *
 * Methodology notes that show up in the report header:
 *   - N iterations per (model, prompt) — captured in `iterations` arg.
 *   - Mean ± sample stddev for latency / TTFT / tokens-per-sec.
 *   - Quality is reported ONLY for the json-extraction category, where pass means
 *     "valid JSON object that contains every required key". Factual and RAG
 *     categories are explicitly labelled as latency/throughput only — substring
 *     matching against a reference answer is too loose to call quality.
 *   - TTFT is approximated as load_duration + prompt_eval_duration from the
 *     non-streaming /api/chat response. A real streaming TTFT would require a
 *     different code path.
 */
public final class ReportWriter {

    private ReportWriter() {}

    public static String render(
            List<String> models,
            List<Prompt> prompts,
            List<BenchResult> results,
            Map<String, Long> modelSizeBytes,
            int iterations,
            String ollamaUrl
    ) {
        StringBuilder md = new StringBuilder();

        // ---- Header ----
        md.append("# Ollama model benchmark\n\n");
        md.append("Generated by `BenchmarkMain` against a local Ollama instance. ")
          .append("Numbers are reproducible from the repo — see `Reproducing` at the bottom.\n\n");

        md.append("## Methodology\n\n");
        md.append("- **Date (UTC):** ").append(Instant.now()).append("\n");
        md.append("- **Ollama endpoint:** ").append(ollamaUrl).append("\n");
        md.append("- **Iterations (N) per (model, prompt):** ").append(iterations).append("\n");
        md.append("- **Models tested:** ").append(String.join(", ", models)).append("\n");
        md.append("- **OS / arch:** ").append(System.getProperty("os.name"))
                .append(" / ").append(System.getProperty("os.arch")).append("\n");
        md.append("- **CPU cores (logical):** ").append(Runtime.getRuntime().availableProcessors()).append("\n");
        md.append("- **JVM:** ").append(System.getProperty("java.version")).append("\n\n");

        md.append("### What is and isn't claimed\n\n");
        md.append("- **Quality** is reported ONLY for the `json` category, where pass means ")
          .append("\"output is a valid JSON object and contains every required key\". ")
          .append("Required keys are defined in `prompts.yaml`.\n");
        md.append("- The `factual` and `rag` categories are reported as **latency/throughput only**. ")
          .append("Substring-matching small models against a reference answer is too unreliable ")
          .append("to call \"correctness\", so those numbers are not in this report.\n");
        md.append("- **TTFT** is approximated as `load_duration + prompt_eval_duration` from the ")
          .append("non-streaming response — a reasonable lower bound for time-until-first-token, ")
          .append("but not a streaming-client measurement.\n");
        md.append("- All timings come from Ollama's own response payload (nanoseconds → ms here). ")
          .append("Wall-clock latency is measured client-side.\n\n");

        // Prompt suite breakdown
        Set<String> categoriesInOrder = new LinkedHashSet<>();
        for (Prompt p : prompts) categoriesInOrder.add(p.category());

        md.append("## Prompt suite\n\n");
        md.append("| Category | Count | Scored for quality? |\n|---|---:|:---:|\n");
        for (String cat : categoriesInOrder) {
            long n = prompts.stream().filter(p -> p.category().equals(cat)).count();
            md.append("| ").append(cat).append(" | ").append(n).append(" | ")
              .append("json".equals(cat) ? "yes" : "no (latency/throughput only)")
              .append(" |\n");
        }
        md.append("\n");

        // ---- Per-model performance ----
        md.append("## Per-model performance (all categories pooled)\n\n");
        md.append("| Model | Disk MB | Successful runs | Latency ms mean ± sd | Latency p-min..p-max | TTFT ms mean ± sd | Tokens/s mean ± sd |\n");
        md.append("|---|---:|---:|---:|---:|---:|---:|\n");
        for (String model : models) {
            List<BenchResult> rs = results.stream()
                    .filter(r -> r.model().equals(model) && r.errorMessage() == null)
                    .toList();
            if (rs.isEmpty()) {
                md.append("| ").append(model).append(" | — | 0 | — | — | — | — |\n");
                continue;
            }
            Stats lat = Stats.of(rs.stream().mapToDouble(r -> (double) r.latencyMs()).toArray());
            Stats ttft = Stats.of(rs.stream().mapToDouble(r -> (double) r.ttftMs()).toArray());
            Stats tps = Stats.of(rs.stream().mapToDouble(BenchResult::tokensPerSec).toArray());

            long sizeBytes = modelSizeBytes.getOrDefault(model, 0L);
            md.append("| ").append(model)
              .append(" | ").append(sizeBytes == 0 ? "—" : String.format("%.0f", sizeBytes / 1_048_576.0))
              .append(" | ").append(rs.size())
              .append(" | ").append(fmtMeanSd(lat)).append(" ms")
              .append(" | ").append(String.format("%.0f..%.0f", lat.min(), lat.max())).append(" ms")
              .append(" | ").append(fmtMeanSd(ttft)).append(" ms")
              .append(" | ").append(fmtMeanSd(tps))
              .append(" |\n");
        }
        md.append("\n");

        // ---- JSON quality ----
        md.append("## JSON-extraction quality\n\n");
        md.append("Pass = output is a valid JSON object **and** contains every required key listed in `prompts.yaml`. ")
          .append("Iterations are pooled (so pass-rate is over `n_prompts × iterations` calls per model).\n\n");
        md.append("| Model | Passed | Total | Pass rate |\n|---|---:|---:|---:|\n");
        for (String model : models) {
            List<BenchResult> jsonRuns = results.stream()
                    .filter(r -> r.model().equals(model) && r.category().equals("json"))
                    .toList();
            long total = jsonRuns.size();
            long passed = jsonRuns.stream().filter(BenchResult::correct).count();
            String rate = total == 0 ? "—" : String.format("%.0f%%", 100.0 * passed / total);
            md.append("| ").append(model)
              .append(" | ").append(passed)
              .append(" | ").append(total)
              .append(" | ").append(rate)
              .append(" |\n");
        }
        md.append("\n");

        // ---- Per-category latency ----
        md.append("## Per-category latency / throughput\n\n");
        for (String model : models) {
            md.append("### ").append(model).append("\n\n");
            md.append("| Category | n | Latency ms mean ± sd | Tokens/s mean ± sd |\n|---|---:|---:|---:|\n");
            for (String cat : categoriesInOrder) {
                List<BenchResult> rs = results.stream()
                        .filter(r -> r.model().equals(model)
                                && r.category().equals(cat)
                                && r.errorMessage() == null)
                        .toList();
                if (rs.isEmpty()) {
                    md.append("| ").append(cat).append(" | 0 | — | — |\n");
                    continue;
                }
                Stats lat = Stats.of(rs.stream().mapToDouble(r -> (double) r.latencyMs()).toArray());
                Stats tps = Stats.of(rs.stream().mapToDouble(BenchResult::tokensPerSec).toArray());
                md.append("| ").append(cat)
                  .append(" | ").append(rs.size())
                  .append(" | ").append(fmtMeanSd(lat)).append(" ms")
                  .append(" | ").append(fmtMeanSd(tps))
                  .append(" |\n");
            }
            md.append("\n");
        }

        // ---- Sample outputs ----
        md.append("## Sample outputs (iteration 0)\n\n");
        List<Prompt> samples = pickSamples(prompts);
        for (Prompt p : samples) {
            md.append("### `").append(p.id()).append("` — ").append(p.category()).append("\n\n");
            md.append("**User prompt:** ").append(oneLine(p.user())).append("\n\n");
            for (String model : models) {
                BenchResult first = results.stream()
                        .filter(r -> r.model().equals(model)
                                && r.promptId().equals(p.id())
                                && r.iteration() == 0)
                        .findFirst().orElse(null);
                md.append("- **").append(model).append(":** ");
                if (first == null) {
                    md.append("_(no run)_\n");
                } else if (first.errorMessage() != null) {
                    md.append("_error: ").append(oneLine(first.errorMessage())).append("_\n");
                } else {
                    boolean scored = "json".equals(p.category());
                    String mark = scored ? (first.correct() ? "✓ " : "✗ ") : "";
                    md.append(mark).append("`")
                      .append(oneLine(first.output()).replace("`", "'"))
                      .append("` _(").append(first.latencyMs()).append(" ms)_\n");
                }
            }
            md.append("\n");
        }

        // ---- Errors ----
        md.append("## Errors\n\n");
        List<BenchResult> errors = results.stream().filter(r -> r.errorMessage() != null).toList();
        if (errors.isEmpty()) {
            md.append("None.\n\n");
        } else {
            md.append("| Model | Prompt | Iteration | Error |\n|---|---|---:|---|\n");
            errors.forEach(r -> md.append("| ").append(r.model())
                    .append(" | ").append(r.promptId())
                    .append(" | ").append(r.iteration())
                    .append(" | ").append(oneLine(r.errorMessage())).append(" |\n"));
            md.append("\n");
        }

        // ---- Reproducing ----
        md.append("## Reproducing\n\n");
        md.append("```bash\n");
        md.append("# Pull models locally first:\n");
        for (String m : models) md.append("ollama pull ").append(m).append("\n");
        md.append("\n# Then from backend/:\n");
        md.append("mvn spring-boot:run \\\n");
        md.append("  -Dspring-boot.run.main-class=com.chatassistant.aichatassistant.bench.BenchmarkMain \\\n");
        md.append("  -Dspring-boot.run.arguments=\"--models=")
                .append(String.join(",", models))
                .append(" --iterations=").append(iterations).append("\"\n");
        md.append("```\n");

        return md.toString();
    }

    public static Path writeToFile(Path file, String markdown) throws IOException {
        if (file.getParent() != null) Files.createDirectories(file.getParent());
        Files.writeString(file, markdown, StandardCharsets.UTF_8);
        return file;
    }

    // ---------------- helpers ----------------

    private static String fmtMeanSd(Stats s) {
        if (s.n() == 0) return "—";
        // For values likely > 1 use one decimal; for tokens/s use one decimal too.
        return String.format("%.1f ± %.1f", s.mean(), s.stddev());
    }

    private static List<Prompt> pickSamples(List<Prompt> prompts) {
        // One sample per category if possible — most informative spot check.
        Set<String> seen = new LinkedHashSet<>();
        return prompts.stream()
                .filter(p -> seen.add(p.category()))
                .toList();
    }

    private static String oneLine(String s) {
        if (s == null) return "";
        String collapsed = s.replace('\n', ' ').replace('\r', ' ').replaceAll("\\s+", " ").trim();
        return collapsed.length() > 220 ? collapsed.substring(0, 220) + "…" : collapsed;
    }
}
